[package]
name = "note-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4"
note-core = { path = "../note-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
